version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gestion_deportiva_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: IS2deportes
      MYSQL_USER: deportes_user
      MYSQL_PASSWORD: deportes1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./IS2deportes.sql:/docker-entrypoint-initdb.d/IS2deportes.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot1234"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
